### ISSUE TITLE
播放源问题

### ISSUE THREAD

**Issue by Rain120** [k-water/vue-music#5]
// 歌源url
    url: `http://thirdparty.gtimg.com/C100${musicData.songmid}.m4a?fromtag=38`
请问一下，博主这个播放源是怎么抓取的，求教，我之前使用的ws.stream这个，现在好像不管用了，还想问下博主这个播放源有用吗现在？

**Comment by k-water** [comment]
ws这个现在没用了

**Comment by jx-zyf** [comment]
播放源怎么抓取啊？腾讯经常封禁

**Comment by agiokobe** [comment]
请问WS没用了，用哪个好呢？

**Comment by k-water** [comment]
看最后一次commit

**Comment by trace59** [comment]
播放源现在都失效了，vkey的获取感觉很麻烦，之前的vkey获取方式，现在接口又失效了，请问最新vkey的获取方式知道吗

**Comment by k-water** [comment]
不知道，还在尝试中 @trace59

**Comment by fantasticsaa** [comment]
要是有后台管理这个app就更完美了
